name: web

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: web

jobs:
  ci:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Node.js
        uses: volta-cli/action@v4.2.1
      - name: Log Node.js version
        run: node -v
      - name: Install third party dependencies
        run: npm ci
      - name: Check for linting warnings and errors
        run: npm run lint
      - name: Check for errors in build process
        run: npm run build
      - name: Run tests
        run: npm run test

  cd:
    if: github.event_name == 'push'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Node.js
        uses: volta-cli/action@v4.2.1
      - name: Install third party dependencies
        run: npm ci
      - name: Check for linting warnings and errors
        run: npm run lint
      - name: Build web application
        run: npm run build
